# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

#export ZSH_CUSTOM=$HOME/.zshrc.d

# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="agnoster"

# CASE_SENSITIVE="true"
# HYPHEN_INSENSITIVE="true"
# DISABLE_AUTO_UPDATE="true"
# export UPDATE_ZSH_DAYS=13
# DISABLE_LS_COLORS="true"
# DISABLE_AUTO_TITLE="true"
# ENABLE_CORRECTION="true"
# COMPLETION_WAITING_DOTS="true"
# DISABLE_UNTRACKED_FILES_DIRTY="true"
# HIST_STAMPS="mm/dd/yyyy"
ZSH_CUSTOM=$HOME/.zshrc.d

# Look for plugins in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(adb,bower,brew,brew-cask,cp,git,github,grunt,heroku,hub,nmap,node,npm,python,rsync,rvm,sublime,sudo,vagrant)

# User configuration

export PATH="/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:`echo $HOME`/.rvm/bin"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# ssh
export SSH_KEY_PATH="~/.ssh/id_rsa"

export PATH=/Library/Frameworks/Python.framework/Versions/Current/bin:/usr/local/bin:$PATH
export WORKON_HOME=$HOME/virtualenvs
source /Library/Frameworks/Python.framework/Versions/2.7/bin/virtualenvwrapper.sh
alias hibernateon="sudo pmset -a hibernatemode 5"
alias hibernateoff="sudo pmset -a hibernatemode 0"

#MYSQL
alias mysql=/usr/local/mysql/bin/mysql
alias mysqladmin=/usr/local/mysql/bin/mysqladmin

#JAVA
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home
export JRE_HOME=$JAVA_HOME

#ANDROID
export ANDROID_HOME=~/Library/Android/sdk
export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools:$PATH

# source .bash-git-prompt/gitprompt.sh

alias mca='cd ~/mca/git/mca-paytv-android'
alias mcap='cd ~/mca/git/mca-paytvapp-android'
alias gvpclient='cd ~/mca/git/mca-gvpclient-android'
alias playerlib='cd ~/mca/git/mca-playerlib/android'

alias logcatgo='function _t() {echo Filtering:$1; adb logcat -vtime | grep `adb shell "ps | grep $1" | cut -c10-15`}; _t'
alias gitg="git log --graph --pretty=oneline --abbrev-commit --decorate"


